#!/usr/bin/env bash
# requires a domain and accepts optional subdomain name passed in
# audits domain or specific subdomain and prints selected info to stdout
# requirements: must use awk, must use at least one bash function
audit_domain () {
    dot='.'
    if [ ! -z $2 ]
    then
	url=$2$dot$1
	echo -n "The subdomain $2 is a "
	dig $url +noall +answer | awk 'FNR==4 { print $4 " record and points to " $5 }'
    else
	for sub in 'www' 'lb-01' 'web-01' 'web-02'
	do
	    url=$sub$dot$1
	    echo -n "The subdomain $sub is a "
	    dig $url +noall +answer | awk 'FNR==4 { print $4 " record and points to " $5 }'
	done
    fi
}

domain_name=${1:-''}
subdomain_name=${2:-''}

if [ -z $domain_name ]
then
    exit 0
else
    audit_domain $domain_name $subdomain_name
fi
