#!/usr/bin/env bash
# HAProxy

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 431764-web-01 34.229.56.17:80 check
        server 431764-web-02 54.146.78.115:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
